CovidCaseMapTest2: CovidCase.h CovidCaseMap.h CovidCaseMapTest2.cpp
	g++ -Wall -g -D_GLIBCXX_DEBUG -std=c++11 -o Test2 CovidCaseMapTest2.cpp

CovidCaseMapTest1: CovidCase.h CovidCaseMap.h CovidCaseMapTest1.cpp
	g++ -Wall -g -D_GLIBCXX_DEBUG -std=c++11 -o Test1 CovidCaseMapTest1.cpp

all: CovidCaseMapTest1 CovidCaseMapTest2